language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_65f725bac799_key -iv $encrypted_65f725bac799_iv
  -in deploy_rsa.enc -out deploy_rsa -d
script:
- cd frontend
- npm install
- npm test
- npm run build
- cd ..
- cd server
- npm install
- npm run migrate
- cd ..
- chmod 0600 deploy_rsa
- rsync -r -e "ssh -o StrictHostKeyChecking=no -i deploy_rsa" --delete-after --quiet
  $TRAVIS_BUILD_DIR prod@13.56.27.60:~
notifications:
  slack:
    secure: Ap9qkWAv01RdFQwA6Jxtp/w8wG7FXzr5a1IDUREwmuasr2jBTcbGTjzJtsyvDVxzVyEA+bMiBZ7XFNd5COS4pBqRShnW2JKV7dC8pM3zPF8LVz1tOIJndhMO2KgCEm+aLOMTkKYauK1beHziPYtDsB0OkeAcavldjpxMCpAGZijkt6F6A3cAPIdBTylI1dkfmhXDkXMonQ6hU9Y0EO3z3nwe08cFFx5RK9tdZzQbHXBKhDppvqJyfxTn7aO1OKI3SBlqBIcmGSYE3K2F7lXPuxcQK+F754VZLSgv5B9tJT49xRlKwGRAbgPXqh0IMJHGn6jDwBylRqK0Mkon8xFWpK8d5UUmUqPk1cXvCt0F3OZ76Eoi2gGiqKvtrqyAXZVKMUL0Uy5h50dBaPDsS8uVUBpU21KKwbpsCzVA+5csC+oqe6rIA0GlXmSAiECIgBVtLWs54fC6sc9K1CPsTbEIfR0rL0pdX48ZGCFv7N8zpDV+IhjWcYzYJSHqasxVqlrTCIHViZ7e2s1B2TG3uAbsgY/o9sjTjfqymmoHrkvM1zVwrP2cEEZNNNiIddMND+nBorf17mSIRN44SKbVrIRc8YPh+EP9l7uBIwXH5bJCcxMhLRzcW6qQW8UBSD43xrAf3x7uHsxwseaeO1Wf5CE8wp118Byy29QO93lRVOdKmlQ=
env:
  matrix:
  - secure: WHTHoVHmemrZi4WKluZO+uSOqYvaoBfT8bWheFodb80Wr+sNhHAAMHcxPh40wPCRXlkVGqCjwpDxCHYit1qtCIY/tIcuKzQKIv69zTyRxx+oPZE6OFlzWa5G3iWnDog3ZlZoYiz6YQ9xeLCZOygNTLlcD22/HOx0J7eTjfx/Q10Zv09jtqbQf1VwkTn8pXAZz9UGJeUmyDPNgbHK3tUq8Ijftk5LqYr/6lSvVyytg63RIybxO3KZT6m9y7XWOOge3t/yW856GMZvsSMJ0JISXfXC8CAIz0yNPvNE4HNXmgUlaK8GwW7snoJ8wzg2U7yWpIJqhOt85D4qpBo4aV98AKEjaalwQHS61w0WqU/ekEnYkFJZLhGuRG4TdAAO3rX0cFUSeWTSK77OpJvFsHMGdIK9moyulPony4gNRpIIMKU5ESKaDl3pZ2iUGIVvEtUAfVW43dtZ1fA7yIC8UOvs+6H/q9ueQKCHXN/9tpIVoppetjBPdJ/3d9VV7kR0mqfBZpwDdccxvesgr0xcnTRPxEp2NMMGkasmITGbP1umwPukwGTX3gcSQLvSb9aFuqVuMy3kQz/YJZZBjCGIyfHslhi5mnI77BW4UBv4BMe58uTMqBV64XUMo/B11iABAxHhepR8aQJ3Q6g5kC/EPEdksB/Ihw/kcnvitx2wOypwRSM=
